package edu.mit.yingyin.tabletop;

import java.util.ArrayList;
import java.util.List;

import javax.vecmath.Point3f;

import edu.mit.yingyin.tabletop.HandTracker.FingerEvent.FingerEventType;

/**
 * <code>HandTracker</code> tracks hand events based on estimated hand model 
 * parameters.
 * @author yingyin
 *
 */
public class HandTracker {
  /**
   * The listener interface for recieving finger events.
   * @author yingyin
   *
   */
  public static interface IHandEventListener {
    public void fingerPressed(List<FingerEvent> feList);
  }
  
  /**
   * An event generated by a finger.
   * @author yingyin
   *
   */
  public static class FingerEvent {
    public enum FingerEventType {PRESSED, RELEASED};
    
    public int frameID;
    public Point3f position, posOnDisplay;
    public FingerEventType type;
    
    public FingerEvent(Point3f fingertip, int frameID, FingerEventType type) { 
      this.position = fingertip;
      this.frameID = frameID;
      this.type = type;
    }
  }

  private static final int DEBOUNCE_COUNT = 3;

  private List<IHandEventListener> listeners = 
      new ArrayList<IHandEventListener>();
  
  /**
   * Reference to the table.
   */
  private Table table;
  /** Counts the duration of contact or noncontact. */
  private int pressedCounter = 0, releasedCounter = 0;
  /** True if finger is pressed, false otherwise. */
  private boolean pressed = false;
  
  public HandTracker() {
    table = Table.instance();
  }
  
  /**
   * Updates forelimbs information and generates events.
   * @param forelimbs information for all the forlimbs detected.
   * @param frameID frame ID for the current update.
   */
  public void update(List<Forelimb> forelimbs, int frameID) {
    List<FingerEvent> fingerEventList = filterPressed(forelimbs, frameID);
    if (!fingerEventList.isEmpty()) {
      for (IHandEventListener l : listeners) 
        l.fingerPressed(fingerEventList);
    }
  }
  
  public void addListener(IHandEventListener l) {
    listeners.add(l);
  }

  public List<FingerEvent> noFilter(List<Forelimb> forelimbs, int frameID) {
    List<FingerEvent> fingerEventList = new ArrayList<FingerEvent>();
    for (Forelimb forelimb : forelimbs) 
      for (Point3f tip : forelimb.filteredFingertips)
        fingerEventList.add(new FingerEvent(tip, frameID, 
                                            FingerEventType.PRESSED));
    return fingerEventList;
  }

  /**
   * Filters out finger pressed events.
   * @param forelimbs
   * @param frameID
   * @return
   */
  public List<FingerEvent> filterPressed(List<Forelimb> forelimbs, 
                                         int frameID) {
    List<FingerEvent> fingerEventList = new ArrayList<FingerEvent>();
    for (Forelimb forelimb : forelimbs)
      for (Point3f tip : forelimb.filteredFingertips) {
        float tipDepth = tip.z + Hand.FINGER_THICKNESS; 
        boolean inContact = table.isInContact((int)tip.x, (int)tip.y, tipDepth);
        if (inContact) {
          pressedCounter++;
          releasedCounter = 0;
        } else {
          releasedCounter++;
          pressedCounter = 0;
        }
        if (pressedCounter == DEBOUNCE_COUNT && !pressed) {
          pressed = true;
          fingerEventList.add(new FingerEvent(tip, frameID, 
                                              FingerEventType.PRESSED));
        } else if (releasedCounter == DEBOUNCE_COUNT && pressed) {
          pressed = false;
          fingerEventList.add(new FingerEvent(tip, frameID, 
                                              FingerEventType.RELEASED));
        }
      }
    return fingerEventList;
  }
}
